version: '3'
services:
  app:
    build: .
    command: rails s -b 0.0.0.0
    container_name: project
    ports:
      - 3000:3000
      - 587:587
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.2-alpine
    command: redis-server
    restart: always
    volumes:
      - 'redis:/data'

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - project:/var/lib/postgresql/data

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'

volumes:
  project:
  redis: